"""Seed data for StreamKart - international authors, audiobooks, books, news."""

# High-quality book/audiobook cover images from Unsplash (open license)
COVERS = {
    "book1": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=800&fit=crop",
    "book2": "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&h=800&fit=crop",
    "book3": "https://images.unsplash.com/photo-1531072901881-d644216d4bf9?w=600&h=800&fit=crop",
    "book4": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=600&h=800&fit=crop",
    "book5": "https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&h=800&fit=crop",
    "book6": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=800&fit=crop",
    "book7": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&h=800&fit=crop",
    "book8": "https://images.unsplash.com/photo-1535905557558-afc4877a26fc?w=600&h=800&fit=crop",
    "book9": "https://images.unsplash.com/photo-1474932430478-367dbb6832c1?w=600&h=800&fit=crop",
    "book10": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=800&fit=crop",
    "audio1": "https://images.unsplash.com/photo-1519682577862-22b62b24e493?w=600&h=800&fit=crop",
    "audio2": "https://images.unsplash.com/photo-1483546363825-7ebf25fb7513?w=600&h=800&fit=crop",
    "audio3": "https://images.unsplash.com/photo-1453928582365-b6ad33cbcf64?w=600&h=800&fit=crop",
    "audio4": "https://images.unsplash.com/photo-1593697972672-b1c1362d97a4?w=600&h=800&fit=crop",
    "news1": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&h=800&fit=crop",
    "news2": "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=600&h=800&fit=crop",
    "news3": "https://images.unsplash.com/photo-1572949645841-094f3a9c4c94?w=600&h=800&fit=crop",
    "news4": "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=600&h=800&fit=crop",
}

SEED_CATEGORIES = [
    {"slug": "all", "name": "All", "description": "Browse the full collection"},
    {"slug": "book", "name": "Books", "description": "Hardcover & paperback editions from international voices"},
    {"slug": "audiobook", "name": "Audiobooks", "description": "Listen to world-class narrators"},
    {"slug": "news", "name": "News Collection", "description": "Curated journalism, magazines & dispatches"},
]

SEED_AUTHORS = [
    {"name": "Haruki Murakami", "country": "Japan"},
    {"name": "Gabriel García Márquez", "country": "Colombia"},
    {"name": "Chimamanda Ngozi Adichie", "country": "Nigeria"},
    {"name": "Stephen King", "country": "USA"},
    {"name": "Agatha Christie", "country": "UK"},
    {"name": "Jorge Luis Borges", "country": "Argentina"},
    {"name": "Margaret Atwood", "country": "Canada"},
    {"name": "Yuval Noah Harari", "country": "Israel"},
    {"name": "Elena Ferrante", "country": "Italy"},
    {"name": "Olga Tokarczuk", "country": "Poland"},
]

SEED_PRODUCTS = [
    # Books
    {
        "id": "p-001", "title": "Norwegian Wood", "author": "Haruki Murakami", "category": "book",
        "genre": "Literary Fiction", "price": 14.99, "original_price": 19.99, "rating": 4.7, "reviews": 2843,
        "cover_image": COVERS["book1"], "pages": 296, "language": "English",
        "publisher": "Vintage International", "year": 2000,
        "description": "A poignant story of one college student's romantic coming-of-age, told with elegance and unparalleled honesty.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-002", "title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "category": "book",
        "genre": "Magical Realism", "price": 16.50, "original_price": 22.00, "rating": 4.8, "reviews": 5210,
        "cover_image": COVERS["book2"], "pages": 417, "language": "English",
        "publisher": "Harper Perennial", "year": 1967,
        "description": "The multi-generational story of the Buendía family in the mythical town of Macondo. A masterwork of 20th-century literature.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-003", "title": "Americanah", "author": "Chimamanda Ngozi Adichie", "category": "book",
        "genre": "Contemporary Fiction", "price": 13.99, "rating": 4.6, "reviews": 1820,
        "cover_image": COVERS["book3"], "pages": 588, "language": "English",
        "publisher": "Anchor", "year": 2013,
        "description": "A powerful, tender story of race and identity by the award-winning author of Half of a Yellow Sun.",
        "featured": False, "bestseller": True,
    },
    {
        "id": "p-004", "title": "The Shining", "author": "Stephen King", "category": "book",
        "genre": "Horror", "price": 12.00, "original_price": 18.00, "rating": 4.7, "reviews": 9120,
        "cover_image": COVERS["book4"], "pages": 688, "language": "English",
        "publisher": "Anchor", "year": 1977,
        "description": "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. Or so he thinks.",
        "featured": True, "bestseller": False,
    },
    {
        "id": "p-005", "title": "And Then There Were None", "author": "Agatha Christie", "category": "book",
        "genre": "Mystery", "price": 10.99, "rating": 4.5, "reviews": 7650,
        "cover_image": COVERS["book5"], "pages": 264, "language": "English",
        "publisher": "William Morrow", "year": 1939,
        "description": "Ten strangers, lured to an isolated island. One by one, they are accused, then killed. A masterpiece of mystery.",
        "featured": False, "bestseller": True,
    },
    {
        "id": "p-006", "title": "Ficciones", "author": "Jorge Luis Borges", "category": "book",
        "genre": "Short Stories", "price": 11.99, "rating": 4.7, "reviews": 1430,
        "cover_image": COVERS["book6"], "pages": 174, "language": "English",
        "publisher": "Grove Press", "year": 1944,
        "description": "Borges' most celebrated stories: labyrinths, mirrors, libraries that contain the universe.",
        "featured": False, "bestseller": False,
    },
    {
        "id": "p-007", "title": "The Handmaid's Tale", "author": "Margaret Atwood", "category": "book",
        "genre": "Dystopian", "price": 13.50, "original_price": 17.00, "rating": 4.6, "reviews": 6230,
        "cover_image": COVERS["book7"], "pages": 311, "language": "English",
        "publisher": "Anchor", "year": 1985,
        "description": "Offred is a Handmaid in the Republic of Gilead. She may leave the home of her Commander once a day.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-008", "title": "Sapiens: A Brief History of Humankind", "author": "Yuval Noah Harari", "category": "book",
        "genre": "Non-fiction", "price": 18.99, "original_price": 24.99, "rating": 4.7, "reviews": 12400,
        "cover_image": COVERS["book8"], "pages": 464, "language": "English",
        "publisher": "Harper", "year": 2014,
        "description": "From a renowned historian, a sweeping history of humankind from the Stone Age to the modern era.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-009", "title": "My Brilliant Friend", "author": "Elena Ferrante", "category": "book",
        "genre": "Literary Fiction", "price": 14.00, "rating": 4.5, "reviews": 3105,
        "cover_image": COVERS["book9"], "pages": 331, "language": "English",
        "publisher": "Europa Editions", "year": 2011,
        "description": "The first novel in the New York Times bestselling Neapolitan quartet.",
        "featured": False, "bestseller": False,
    },
    {
        "id": "p-010", "title": "Drive Your Plow Over the Bones of the Dead", "author": "Olga Tokarczuk", "category": "book",
        "genre": "Literary Fiction", "price": 15.50, "rating": 4.4, "reviews": 940,
        "cover_image": COVERS["book10"], "pages": 274, "language": "English",
        "publisher": "Riverhead Books", "year": 2009,
        "description": "An astonishing fable from Nobel laureate Olga Tokarczuk — both a thriller and a meditation on humanity.",
        "featured": False, "bestseller": False,
    },

    # Audiobooks
    {
        "id": "p-011", "title": "Kafka on the Shore (Audiobook)", "author": "Haruki Murakami", "category": "audiobook",
        "genre": "Literary Fiction", "price": 19.99, "original_price": 29.99, "rating": 4.8, "reviews": 2210,
        "cover_image": COVERS["audio1"], "duration": "19h 06m", "language": "English",
        "publisher": "Random House Audio", "year": 2005,
        "description": "Two bewitching, parallel narratives — a fifteen-year-old boy and an old simpleton — interweave in a mesmerizing odyssey.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-012", "title": "Beloved (Audiobook)", "author": "Toni Morrison", "category": "audiobook",
        "genre": "Historical Fiction", "price": 17.99, "rating": 4.7, "reviews": 1820,
        "cover_image": COVERS["audio2"], "duration": "10h 56m", "language": "English",
        "publisher": "Random House Audio", "year": 1987,
        "description": "Toni Morrison's Pulitzer Prize-winning novel narrated with luminous prose and unforgettable power.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-013", "title": "The Name of the Rose (Audiobook)", "author": "Umberto Eco", "category": "audiobook",
        "genre": "Mystery", "price": 21.50, "rating": 4.6, "reviews": 1310,
        "cover_image": COVERS["audio3"], "duration": "21h 36m", "language": "English",
        "publisher": "Recorded Books", "year": 1980,
        "description": "Murder, heresy, and a labyrinthine library in 14th-century Italy. A literary thriller of dazzling intelligence.",
        "featured": False, "bestseller": False,
    },
    {
        "id": "p-014", "title": "Pachinko (Audiobook)", "author": "Min Jin Lee", "category": "audiobook",
        "genre": "Historical Fiction", "price": 18.99, "original_price": 24.99, "rating": 4.7, "reviews": 4520,
        "cover_image": COVERS["audio4"], "duration": "18h 16m", "language": "English",
        "publisher": "Hachette Audio", "year": 2017,
        "description": "An exquisite, haunting epic following four generations of a Korean family in Japan.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-015", "title": "The Vegetarian (Audiobook)", "author": "Han Kang", "category": "audiobook",
        "genre": "Literary Fiction", "price": 14.99, "rating": 4.5, "reviews": 980,
        "cover_image": COVERS["audio1"], "duration": "5h 14m", "language": "English",
        "publisher": "Hogarth", "year": 2007,
        "description": "Winner of the International Booker Prize. A surreal and beautiful tale from Nobel laureate Han Kang.",
        "featured": False, "bestseller": False,
    },
    {
        "id": "p-016", "title": "The Alchemist (Audiobook)", "author": "Paulo Coelho", "category": "audiobook",
        "genre": "Philosophical", "price": 12.99, "original_price": 18.99, "rating": 4.6, "reviews": 8930,
        "cover_image": COVERS["audio2"], "duration": "4h 02m", "language": "English",
        "publisher": "HarperAudio", "year": 1988,
        "description": "An enchanting fable about following your dreams — narrated by the author himself.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-017", "title": "Convenience Store Woman (Audiobook)", "author": "Sayaka Murata", "category": "audiobook",
        "genre": "Contemporary", "price": 11.99, "rating": 4.4, "reviews": 760,
        "cover_image": COVERS["audio3"], "duration": "3h 22m", "language": "English",
        "publisher": "Grove Atlantic", "year": 2018,
        "description": "A haunting, satirical glimpse of an unusual office worker who refuses to follow social conventions.",
        "featured": False, "bestseller": False,
    },
    {
        "id": "p-018", "title": "If on a Winter's Night a Traveler (Audiobook)", "author": "Italo Calvino", "category": "audiobook",
        "genre": "Postmodern", "price": 16.99, "rating": 4.5, "reviews": 540,
        "cover_image": COVERS["audio4"], "duration": "8h 45m", "language": "English",
        "publisher": "Audible Studios", "year": 1979,
        "description": "A masterpiece of metafiction — ten interrupted novels and a love story, all in one.",
        "featured": False, "bestseller": False,
    },

    # News collection
    {
        "id": "p-019", "title": "The Atlantic — Annual Print Bundle", "author": "The Atlantic Editors", "category": "news",
        "genre": "Magazine", "price": 49.99, "original_price": 79.99, "rating": 4.6, "reviews": 320,
        "cover_image": COVERS["news1"], "language": "English",
        "publisher": "The Atlantic", "year": 2024,
        "description": "Twelve months of The Atlantic delivered in print — long-form journalism, politics, culture and ideas.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-020", "title": "The Economist — World in 2026", "author": "The Economist", "category": "news",
        "genre": "Magazine", "price": 24.99, "rating": 4.5, "reviews": 410,
        "cover_image": COVERS["news2"], "language": "English",
        "publisher": "The Economist", "year": 2026,
        "description": "An annual collection of essays predicting the year ahead — politics, business, science and the arts.",
        "featured": True, "bestseller": False,
    },
    {
        "id": "p-021", "title": "Le Monde Diplomatique — English Quarterly", "author": "Le Monde Editorial", "category": "news",
        "genre": "International Affairs", "price": 18.99, "rating": 4.4, "reviews": 180,
        "cover_image": COVERS["news3"], "language": "English",
        "publisher": "Le Monde", "year": 2025,
        "description": "Four issues of incisive international reporting and analysis from the celebrated French dispatch.",
        "featured": False, "bestseller": False,
    },
    {
        "id": "p-022", "title": "The New Yorker — Fiction Issue Collection", "author": "The New Yorker", "category": "news",
        "genre": "Magazine", "price": 32.50, "rating": 4.7, "reviews": 690,
        "cover_image": COVERS["news4"], "language": "English",
        "publisher": "Condé Nast", "year": 2025,
        "description": "Five legendary Fiction Issues bundled — short stories from the world's finest international authors.",
        "featured": True, "bestseller": True,
    },
    {
        "id": "p-023", "title": "Granta — Best of Young Novelists", "author": "Granta Magazine", "category": "news",
        "genre": "Literary Magazine", "price": 22.00, "rating": 4.5, "reviews": 240,
        "cover_image": COVERS["news1"], "language": "English",
        "publisher": "Granta", "year": 2024,
        "description": "The definitive showcase of new international literary voices — only published once a decade.",
        "featured": False, "bestseller": False,
    },
    {
        "id": "p-024", "title": "Foreign Affairs — Geopolitics Quarterly", "author": "Foreign Affairs", "category": "news",
        "genre": "Politics", "price": 27.99, "rating": 4.6, "reviews": 310,
        "cover_image": COVERS["news2"], "language": "English",
        "publisher": "Council on Foreign Relations", "year": 2025,
        "description": "The world's leading journal of international affairs — bound print collection.",
        "featured": False, "bestseller": False,
    },
]
