"""Seed data for StreamKart - digital books & audiobooks. All prices in INR (base currency)."""

def cover(isbn):
    return f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"


SEED_CATEGORIES = [
    {"slug": "all", "name": "All", "description": "Browse the full digital collection"},
    {"slug": "book", "name": "Books", "description": "Read instantly online — no waiting, no shipping"},
    {"slug": "audiobook", "name": "Audiobooks", "description": "Stream world-class narration anywhere"},
]

SEED_AUTHORS = [
    {"name": "Haruki Murakami", "country": "Japan"},
    {"name": "Gabriel García Márquez", "country": "Colombia"},
    {"name": "Chimamanda Ngozi Adichie", "country": "Nigeria"},
    {"name": "Stephen King", "country": "USA"},
    {"name": "Agatha Christie", "country": "UK"},
    {"name": "Jorge Luis Borges", "country": "Argentina"},
    {"name": "Margaret Atwood", "country": "Canada"},
    {"name": "Yuval Noah Harari", "country": "Israel"},
    {"name": "Elena Ferrante", "country": "Italy"},
    {"name": "Olga Tokarczuk", "country": "Poland"},
    {"name": "Salman Rushdie", "country": "India / UK"},
    {"name": "Arundhati Roy", "country": "India"},
    {"name": "Khaled Hosseini", "country": "Afghanistan / USA"},
    {"name": "Liu Cixin", "country": "China"},
    {"name": "Roberto Bolaño", "country": "Chile"},
]

SEED_PRODUCTS = [
    # ----- Books (INR) -----
    {"id": "p-001", "title": "Norwegian Wood", "author": "Haruki Murakami", "category": "book",
     "genre": "Literary Fiction", "price": 1199, "original_price": 1599, "rating": 4.7, "reviews": 2843,
     "cover_image": cover("9780375704024"), "pages": 296, "language": "English",
     "publisher": "Vintage International", "year": 2000,
     "description": "A poignant story of one college student's romantic coming-of-age, told with elegance and unparalleled honesty. Read instantly on web, mobile or tablet.",
     "featured": True, "bestseller": True},
    {"id": "p-002", "title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "category": "book",
     "genre": "Magical Realism", "price": 1399, "original_price": 1799, "rating": 4.8, "reviews": 5210,
     "cover_image": cover("9780060883287"), "pages": 417, "language": "English",
     "publisher": "Harper Perennial", "year": 1967,
     "description": "The multi-generational story of the Buendía family in the mythical town of Macondo. A masterwork of 20th-century literature, available to read online.",
     "featured": True, "bestseller": True},
    {"id": "p-003", "title": "Americanah", "author": "Chimamanda Ngozi Adichie", "category": "book",
     "genre": "Contemporary Fiction", "price": 1149, "rating": 4.6, "reviews": 1820,
     "cover_image": cover("9780307455925"), "pages": 588, "language": "English",
     "publisher": "Anchor", "year": 2013,
     "description": "A powerful, tender story of race and identity by the author of Half of a Yellow Sun.",
     "featured": False, "bestseller": True},
    {"id": "p-004", "title": "The Shining", "author": "Stephen King", "category": "book",
     "genre": "Horror", "price": 999, "original_price": 1499, "rating": 4.7, "reviews": 9120,
     "cover_image": cover("9780307743657"), "pages": 688, "language": "English",
     "publisher": "Anchor", "year": 1977,
     "description": "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. Or so he thinks.",
     "featured": True, "bestseller": False},
    {"id": "p-005", "title": "And Then There Were None", "author": "Agatha Christie", "category": "book",
     "genre": "Mystery", "price": 899, "rating": 4.5, "reviews": 7650,
     "cover_image": cover("9780062073488"), "pages": 264, "language": "English",
     "publisher": "William Morrow", "year": 1939,
     "description": "Ten strangers, lured to an isolated island. One by one, accused — then killed. The world's bestselling mystery.",
     "featured": False, "bestseller": True},
    {"id": "p-006", "title": "Ficciones", "author": "Jorge Luis Borges", "category": "book",
     "genre": "Short Stories", "price": 999, "rating": 4.7, "reviews": 1430,
     "cover_image": cover("9780802130303"), "pages": 174, "language": "English",
     "publisher": "Grove Press", "year": 1944,
     "description": "Borges' most celebrated stories — labyrinths, mirrors, libraries that contain the universe.",
     "featured": False, "bestseller": False},
    {"id": "p-007", "title": "The Handmaid's Tale", "author": "Margaret Atwood", "category": "book",
     "genre": "Dystopian", "price": 1099, "original_price": 1399, "rating": 4.6, "reviews": 6230,
     "cover_image": cover("9780385490818"), "pages": 311, "language": "English",
     "publisher": "Anchor", "year": 1985,
     "description": "Offred is a Handmaid in the Republic of Gilead. She may leave the home of her Commander once a day.",
     "featured": True, "bestseller": True},
    {"id": "p-008", "title": "Sapiens: A Brief History of Humankind", "author": "Yuval Noah Harari", "category": "book",
     "genre": "Non-fiction", "price": 1599, "original_price": 1999, "rating": 4.7, "reviews": 12400,
     "cover_image": cover("9780062316097"), "pages": 464, "language": "English",
     "publisher": "Harper", "year": 2014,
     "description": "A sweeping history of humankind from the Stone Age to the modern era.",
     "featured": True, "bestseller": True},
    {"id": "p-009", "title": "My Brilliant Friend", "author": "Elena Ferrante", "category": "book",
     "genre": "Literary Fiction", "price": 1199, "rating": 4.5, "reviews": 3105,
     "cover_image": cover("9781609450786"), "pages": 331, "language": "English",
     "publisher": "Europa Editions", "year": 2011,
     "description": "The first novel in the New York Times bestselling Neapolitan quartet.",
     "featured": False, "bestseller": False},
    {"id": "p-010", "title": "Drive Your Plow Over the Bones of the Dead", "author": "Olga Tokarczuk", "category": "book",
     "genre": "Literary Fiction", "price": 1299, "rating": 4.4, "reviews": 940,
     "cover_image": cover("9780525541349"), "pages": 274, "language": "English",
     "publisher": "Riverhead Books", "year": 2009,
     "description": "An astonishing fable from Nobel laureate Olga Tokarczuk — both a thriller and a meditation on humanity.",
     "featured": False, "bestseller": False},
    {"id": "p-019", "title": "Midnight's Children", "author": "Salman Rushdie", "category": "book",
     "genre": "Magical Realism", "price": 1349, "original_price": 1699, "rating": 4.6, "reviews": 4280,
     "cover_image": cover("9780812976533"), "pages": 552, "language": "English",
     "publisher": "Random House", "year": 1981,
     "description": "Born at the stroke of India's independence, Saleem Sinai's life mirrors his nation's. Booker of Bookers.",
     "featured": True, "bestseller": True},
    {"id": "p-020", "title": "The God of Small Things", "author": "Arundhati Roy", "category": "book",
     "genre": "Literary Fiction", "price": 1099, "rating": 4.5, "reviews": 5610,
     "cover_image": cover("9780812979657"), "pages": 333, "language": "English",
     "publisher": "Random House", "year": 1997,
     "description": "Booker Prize-winning debut — a haunting tale of a family in Kerala forever changed by a single tragic afternoon.",
     "featured": True, "bestseller": True},
    {"id": "p-021", "title": "The Kite Runner", "author": "Khaled Hosseini", "category": "book",
     "genre": "Historical Fiction", "price": 1199, "original_price": 1499, "rating": 4.8, "reviews": 14200,
     "cover_image": cover("9781594631931"), "pages": 371, "language": "English",
     "publisher": "Riverhead", "year": 2003,
     "description": "An unforgettable, heartbreaking story of friendship and redemption set against the tumult of Afghanistan.",
     "featured": True, "bestseller": True},
    {"id": "p-022", "title": "The Three-Body Problem", "author": "Liu Cixin", "category": "book",
     "genre": "Science Fiction", "price": 1299, "rating": 4.6, "reviews": 7820,
     "cover_image": cover("9780765382030"), "pages": 416, "language": "English",
     "publisher": "Tor Books", "year": 2008,
     "description": "China's bestselling science-fiction novel — a Hugo-winning first contact epic that became a global phenomenon.",
     "featured": True, "bestseller": True},
    {"id": "p-023", "title": "Exit West", "author": "Mohsin Hamid", "category": "book",
     "genre": "Literary Fiction", "price": 1049, "rating": 4.4, "reviews": 2310,
     "cover_image": cover("9780735212176"), "pages": 240, "language": "English",
     "publisher": "Riverhead Books", "year": 2017,
     "description": "A young couple emerges in a city teetering at the edge of war. Booker shortlist.",
     "featured": False, "bestseller": False},
    {"id": "p-024", "title": "2666", "author": "Roberto Bolaño", "category": "book",
     "genre": "Literary Fiction", "price": 1499, "rating": 4.5, "reviews": 1180,
     "cover_image": cover("9780312429218"), "pages": 912, "language": "English",
     "publisher": "FSG", "year": 2004,
     "description": "Bolaño's posthumous masterpiece — five interlocking books circling a series of unsolved murders in Mexico.",
     "featured": False, "bestseller": False},
    {"id": "p-025", "title": "Less", "author": "Andrew Sean Greer", "category": "book",
     "genre": "Comedy", "price": 999, "original_price": 1299, "rating": 4.3, "reviews": 1840,
     "cover_image": cover("9780316316125"), "pages": 273, "language": "English",
     "publisher": "Lee Boudreaux Books", "year": 2017,
     "description": "Pulitzer Prize-winning comic novel about a failed novelist circling the globe to avoid an ex's wedding.",
     "featured": False, "bestseller": True},
    {"id": "p-026", "title": "Lincoln in the Bardo", "author": "George Saunders", "category": "book",
     "genre": "Historical Fiction", "price": 1149, "rating": 4.4, "reviews": 2940,
     "cover_image": cover("9780812995343"), "pages": 343, "language": "English",
     "publisher": "Random House", "year": 2017,
     "description": "Man Booker Prize winner — Abraham Lincoln, his dying son Willie, and a chorus of voices from beyond.",
     "featured": False, "bestseller": False},
    {"id": "p-027", "title": "Autumn", "author": "Ali Smith", "category": "book",
     "genre": "Literary Fiction", "price": 999, "rating": 4.2, "reviews": 1120,
     "cover_image": cover("9780241973318"), "pages": 264, "language": "English",
     "publisher": "Hamish Hamilton", "year": 2016,
     "description": "First in the Seasonal Quartet — a Booker-shortlisted meditation on art, friendship and a divided Britain.",
     "featured": False, "bestseller": False},
    {"id": "p-028", "title": "Kitchen", "author": "Banana Yoshimoto", "category": "book",
     "genre": "Literary Fiction", "price": 849, "rating": 4.3, "reviews": 1860,
     "cover_image": cover("9780802142443"), "pages": 152, "language": "English",
     "publisher": "Grove Press", "year": 1988,
     "description": "Two novellas of love, loss and ramen — modern Japanese classic.",
     "featured": False, "bestseller": False},
    {"id": "p-029", "title": "The Shadow of the Wind", "author": "Carlos Ruiz Zafón", "category": "book",
     "genre": "Mystery", "price": 1149, "original_price": 1499, "rating": 4.7, "reviews": 6730,
     "cover_image": cover("9780143034902"), "pages": 487, "language": "English",
     "publisher": "Penguin", "year": 2001,
     "description": "Barcelona, 1945. A boy discovers a mysterious book in the Cemetery of Forgotten Books — and his life is forever changed.",
     "featured": True, "bestseller": True},
    {"id": "p-030", "title": "Disgrace", "author": "J.M. Coetzee", "category": "book",
     "genre": "Literary Fiction", "price": 1049, "rating": 4.4, "reviews": 2230,
     "cover_image": cover("9780140296402"), "pages": 220, "language": "English",
     "publisher": "Penguin", "year": 1999,
     "description": "Booker Prize winner from Nobel laureate Coetzee — a devastating novel of post-apartheid South Africa.",
     "featured": False, "bestseller": False},
    {"id": "p-031", "title": "Snow Country", "author": "Yasunari Kawabata", "category": "book",
     "genre": "Literary Fiction", "price": 949, "rating": 4.4, "reviews": 1320,
     "cover_image": cover("9780679761044"), "pages": 175, "language": "English",
     "publisher": "Vintage International", "year": 1947,
     "description": "Nobel laureate Kawabata's haunting masterpiece — a love story set against Japan's wintry north.",
     "featured": False, "bestseller": False},
    {"id": "p-032", "title": "The Fishermen", "author": "Chigozie Obioma", "category": "book",
     "genre": "Literary Fiction", "price": 999, "rating": 4.4, "reviews": 980,
     "cover_image": cover("9780316338394"), "pages": 304, "language": "English",
     "publisher": "Little Brown", "year": 2015,
     "description": "Booker-shortlisted debut — four brothers in 1990s Nigeria meet a madman whose prophecy will haunt them.",
     "featured": False, "bestseller": False},

    # ----- Audiobooks (INR) -----
    {"id": "p-011", "title": "Kafka on the Shore (Audiobook)", "author": "Haruki Murakami", "category": "audiobook",
     "genre": "Literary Fiction", "price": 1699, "original_price": 2499, "rating": 4.8, "reviews": 2210,
     "cover_image": cover("9781400079278"), "duration": "19h 06m", "language": "English",
     "publisher": "Random House Audio", "year": 2005,
     "description": "Two bewitching parallel narratives interweave in a mesmerizing odyssey. Stream instantly.",
     "featured": True, "bestseller": True},
    {"id": "p-012", "title": "Beloved (Audiobook)", "author": "Toni Morrison", "category": "audiobook",
     "genre": "Historical Fiction", "price": 1499, "rating": 4.7, "reviews": 1820,
     "cover_image": cover("9781400033416"), "duration": "10h 56m", "language": "English",
     "publisher": "Random House Audio", "year": 1987,
     "description": "Toni Morrison's Pulitzer Prize-winning novel narrated with luminous prose and unforgettable power.",
     "featured": True, "bestseller": True},
    {"id": "p-013", "title": "The Name of the Rose (Audiobook)", "author": "Umberto Eco", "category": "audiobook",
     "genre": "Mystery", "price": 1799, "rating": 4.6, "reviews": 1310,
     "cover_image": cover("9780156001311"), "duration": "21h 36m", "language": "English",
     "publisher": "Recorded Books", "year": 1980,
     "description": "Murder, heresy, and a labyrinthine library in 14th-century Italy.",
     "featured": False, "bestseller": False},
    {"id": "p-014", "title": "Pachinko (Audiobook)", "author": "Min Jin Lee", "category": "audiobook",
     "genre": "Historical Fiction", "price": 1599, "original_price": 2099, "rating": 4.7, "reviews": 4520,
     "cover_image": cover("9781455563920"), "duration": "18h 16m", "language": "English",
     "publisher": "Hachette Audio", "year": 2017,
     "description": "An exquisite, haunting epic following four generations of a Korean family in Japan.",
     "featured": True, "bestseller": True},
    {"id": "p-015", "title": "The Vegetarian (Audiobook)", "author": "Han Kang", "category": "audiobook",
     "genre": "Literary Fiction", "price": 1249, "rating": 4.5, "reviews": 980,
     "cover_image": cover("9781101906118"), "duration": "5h 14m", "language": "English",
     "publisher": "Hogarth", "year": 2007,
     "description": "Winner of the International Booker Prize. A surreal, beautiful tale from Nobel laureate Han Kang.",
     "featured": False, "bestseller": False},
    {"id": "p-016", "title": "The Alchemist (Audiobook)", "author": "Paulo Coelho", "category": "audiobook",
     "genre": "Philosophical", "price": 1099, "original_price": 1599, "rating": 4.6, "reviews": 8930,
     "cover_image": cover("9780062315007"), "duration": "4h 02m", "language": "English",
     "publisher": "HarperAudio", "year": 1988,
     "description": "An enchanting fable about following your dreams — narrated by the author himself.",
     "featured": True, "bestseller": True},
    {"id": "p-017", "title": "Convenience Store Woman (Audiobook)", "author": "Sayaka Murata", "category": "audiobook",
     "genre": "Contemporary", "price": 999, "rating": 4.4, "reviews": 760,
     "cover_image": cover("9780802128256"), "duration": "3h 22m", "language": "English",
     "publisher": "Grove Atlantic", "year": 2018,
     "description": "A haunting, satirical glimpse of an unusual office worker who refuses to follow social conventions.",
     "featured": False, "bestseller": False},
    {"id": "p-018", "title": "If on a Winter's Night a Traveler (Audiobook)", "author": "Italo Calvino", "category": "audiobook",
     "genre": "Postmodern", "price": 1399, "rating": 4.5, "reviews": 540,
     "cover_image": cover("9780156439619"), "duration": "8h 45m", "language": "English",
     "publisher": "Audible Studios", "year": 1979,
     "description": "A masterpiece of metafiction — ten interrupted novels and a love story, all in one.",
     "featured": False, "bestseller": False},
    {"id": "p-033", "title": "Where the Crawdads Sing (Audiobook)", "author": "Delia Owens", "category": "audiobook",
     "genre": "Mystery", "price": 1499, "original_price": 1899, "rating": 4.8, "reviews": 18900,
     "cover_image": cover("9780735219090"), "duration": "12h 12m", "language": "English",
     "publisher": "Penguin Audio", "year": 2018,
     "description": "A bestselling literary mystery about a young girl raised in the marshes of North Carolina.",
     "featured": True, "bestseller": True},
    {"id": "p-034", "title": "Becoming (Audiobook)", "author": "Michelle Obama", "category": "audiobook",
     "genre": "Memoir", "price": 1799, "rating": 4.9, "reviews": 24500,
     "cover_image": cover("9781524763138"), "duration": "19h 03m", "language": "English",
     "publisher": "Random House Audio", "year": 2018,
     "description": "Read by the author — the deeply personal memoir of the former First Lady.",
     "featured": True, "bestseller": True},
]
